import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { HomePage } from '@/components/home/home-page.jsx'
import clientPromise from "../../libs/mongodb";
const inter = Inter({ subsets: ['latin'] })

export default function Home( {data, isConnected} ) {
  return (
    <div>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {isConnected ? (
          <h2 className="subtitle">You are connected to MongoDB</h2>
        ) : (
          <h2 className="subtitle">
            You are NOT connected to MongoDB. Check the <code>README.md</code>{' '}
            for instructions.
          </h2>
      )}
      <HomePage data={data}/>
    </div>
  )
}


export async function getServerSideProps() {
  const { events_categories } = await import('/tmp/data.json');
  try {
    await clientPromise;

    return {
      props: {
        data: events_categories,
        isConnected: true
      }
    }
  } catch (e) {
    console.error(e)

    return {
      props: {
        data: events_categories,
        isConnected: false
      }
    }
  }

}